server:
  port: 9098

spring:
  rabbitmq:
    host: 192.168.137.131
    username: admin
    password: admin
    port: 5672
    #开启发送端到broker的确认
    publisher-confirm-type: simple
    #开启发送端消息抵达消息队列的确认
    publisher-returns: true
    listener:
      simple:
        #开启消费者手动确认模式
        acknowledge-mode: manual
    template:
      #只要抵达队列，以异步发送方式优先回调我们这个returnConfirm
      mandatory: true
logging:
  level:
    com.example.springboot_rabbitmq.service.impl: error
